/**
 * Test fixtures for Quantana Shield.
 * Provides realistic insurance fraud detection test data.
 */

export const TENANT = {
  id: "tenant-001",
  name: "Acme Insurance MGA",
  slug: "acme-insurance",
  domain: "acme.quantanashield.com",
  logoUrl: null,
  primaryColor: "#1e40af",
  secondaryColor: "#3b82f6",
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
};

export const USERS = {
  admin: {
    id: "user-admin",
    tenantId: TENANT.id,
    email: "admin@acme.com",
    name: "Admin User",
    role: "ADMIN" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  underwriter: {
    id: "user-uw",
    tenantId: TENANT.id,
    email: "underwriter@acme.com",
    name: "Jane Underwriter",
    role: "UNDERWRITER" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  seniorUnderwriter: {
    id: "user-suw",
    tenantId: TENANT.id,
    email: "senior@acme.com",
    name: "Senior UW",
    role: "SENIOR_UNDERWRITER" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  siuInvestigator: {
    id: "user-siu",
    tenantId: TENANT.id,
    email: "siu@acme.com",
    name: "SIU Investigator",
    role: "SIU_INVESTIGATOR" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  broker: {
    id: "user-broker",
    tenantId: TENANT.id,
    email: "broker@agency.com",
    name: "Bob Broker",
    role: "BROKER" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
  complianceOfficer: {
    id: "user-co",
    tenantId: TENANT.id,
    email: "compliance@acme.com",
    name: "Compliance Officer",
    role: "COMPLIANCE_OFFICER" as const,
    passwordHash: "$2b$10$hashedpassword",
    mfaSecret: null,
    isActive: true,
    createdAt: new Date("2025-01-01"),
  },
};

export const SUBMISSION = {
  clean: {
    id: "sub-clean",
    tenantId: TENANT.id,
    submitterId: USERS.broker.id,
    insuredName: "ABC Manufacturing LLC",
    lineOfBusiness: "General Liability",
    status: "PROCESSING" as const,
    riskScore: null,
    severity: null,
    channel: "PORTAL" as const,
    assignedUnderwriterId: null,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  fraudulent: {
    id: "sub-fraud",
    tenantId: TENANT.id,
    submitterId: USERS.broker.id,
    insuredName: "Shady Corp Inc",
    lineOfBusiness: "Workers Compensation",
    status: "PROCESSING" as const,
    riskScore: null,
    severity: null,
    channel: "PORTAL" as const,
    assignedUnderwriterId: null,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2025-06-15"),
  },
  reviewed: {
    id: "sub-reviewed",
    tenantId: TENANT.id,
    submitterId: USERS.broker.id,
    insuredName: "Honest Business LLC",
    lineOfBusiness: "Commercial Property",
    status: "UNDER_REVIEW" as const,
    riskScore: 45,
    severity: "MEDIUM" as const,
    channel: "PORTAL" as const,
    assignedUnderwriterId: USERS.underwriter.id,
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-12"),
  },
};

export const DOCUMENTS = {
  acord125: {
    id: "doc-acord125",
    submissionId: SUBMISSION.clean.id,
    tenantId: TENANT.id,
    fileName: "ACORD_125_Application.pdf",
    fileType: "application/pdf",
    fileSize: 245000,
    s3Key: "tenant-001/sub-clean/doc-acord125/ACORD_125_Application.pdf",
    documentType: "ACORD_125" as const,
    classificationConfidence: 0.95,
    extractedData: {
      insuredName: "ABC Manufacturing LLC",
      annualRevenue: 5000000,
      numberOfEmployees: 50,
      lossDisclosure: true,
      effectiveDate: "2025-07-01",
      expirationDate: "2026-07-01",
      naicsCode: "332710",
      _metadata: { confidence: 0.85 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-01"),
  },
  acord130: {
    id: "doc-acord130",
    submissionId: SUBMISSION.clean.id,
    tenantId: TENANT.id,
    fileName: "ACORD_130_WC.pdf",
    fileType: "application/pdf",
    fileSize: 180000,
    s3Key: "tenant-001/sub-clean/doc-acord130/ACORD_130_WC.pdf",
    documentType: "ACORD_130" as const,
    classificationConfidence: 0.92,
    extractedData: {
      insuredName: "ABC Manufacturing LLC",
      totalPayroll: 2500000,
      experienceModRate: 1.05,
      payrollByClassification: [
        { classCode: "3632", description: "Machine Shop", payroll: 1500000, employeeCount: 30 },
        { classCode: "8810", description: "Clerical", payroll: 1000000, employeeCount: 20 },
      ],
      _metadata: { confidence: 0.88 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-01"),
  },
  financialStatement: {
    id: "doc-financial",
    submissionId: SUBMISSION.clean.id,
    tenantId: TENANT.id,
    fileName: "Financial_Statement_2024.pdf",
    fileType: "application/pdf",
    fileSize: 320000,
    s3Key: "tenant-001/sub-clean/doc-financial/Financial_Statement_2024.pdf",
    documentType: "FINANCIAL_STATEMENT" as const,
    classificationConfidence: 0.88,
    extractedData: {
      revenue: 5200000,
      costOfGoodsSold: 3100000,
      grossProfit: 2100000,
      netIncome: 450000,
      totalAssets: 4500000,
      totalLiabilities: 2200000,
      _metadata: { confidence: 0.82 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-01"),
  },
  // Fraudulent scenario: revenue mismatch
  acord125Fraud: {
    id: "doc-acord125-fraud",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    fileName: "Application.pdf",
    fileType: "application/pdf",
    fileSize: 210000,
    s3Key: "tenant-001/sub-fraud/doc-acord125-fraud/Application.pdf",
    documentType: "ACORD_125" as const,
    classificationConfidence: 0.93,
    extractedData: {
      insuredName: "Shady Corp Inc",
      annualRevenue: 10000000,
      numberOfEmployees: 25,
      lossDisclosure: false,
      effectiveDate: "2025-08-01",
      expirationDate: "2026-08-01",
      naicsCode: "238220",
      _metadata: { confidence: 0.80 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-15"),
  },
  financialStatementFraud: {
    id: "doc-financial-fraud",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    fileName: "Financials.pdf",
    fileType: "application/pdf",
    fileSize: 280000,
    s3Key: "tenant-001/sub-fraud/doc-financial-fraud/Financials.pdf",
    documentType: "FINANCIAL_STATEMENT" as const,
    classificationConfidence: 0.85,
    extractedData: {
      revenue: 6000000, // 40% mismatch with ACORD 125's $10M
      costOfGoodsSold: 4200000,
      grossProfit: 1800000,
      netIncome: 200000,
      totalAssets: 3000000,
      totalLiabilities: 2800000,
      _metadata: { confidence: 0.78 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-15"),
  },
  lossRunFraud: {
    id: "doc-lossrun-fraud",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    fileName: "Loss_Runs.pdf",
    fileType: "application/pdf",
    fileSize: 150000,
    s3Key: "tenant-001/sub-fraud/doc-lossrun-fraud/Loss_Runs.pdf",
    documentType: "LOSS_RUN" as const,
    classificationConfidence: 0.90,
    extractedData: {
      totalClaimCount: 3,
      claims: [
        { date: "2024-01-15", amount: 45000, status: "closed", description: "Slip and fall" },
        { date: "2024-06-20", amount: 120000, status: "open", description: "Equipment damage" },
        { date: "2024-09-10", amount: 75000, status: "closed", description: "Employee injury" },
      ],
      totalIncurred: 240000,
      _metadata: { confidence: 0.85 },
    },
    status: "ANALYZED" as const,
    createdAt: new Date("2025-06-15"),
  },
};

export const THRESHOLD_CONFIG = {
  default: {
    id: "threshold-001",
    tenantId: TENANT.id,
    lineOfBusiness: null,
    autoApproveBelow: 20,
    autoEscalateAbove: 70,
    siuReferralOnCritical: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
};

export const FRAUD_INDICATORS = {
  revenueMismatch: {
    id: "fi-revenue",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    documentId: null,
    category: "CROSS_DOC" as const,
    indicatorName: "REVENUE_MISMATCH",
    description: "Revenue mismatch between ACORD 125 and financial statement",
    severity: "CRITICAL" as const,
    evidence: { acordRevenue: 10000000, financialStatementRevenue: 6000000, variancePercent: 40 },
    confidence: 0.85,
    recommendedAction: "Request updated financial statements",
    isOverridden: false,
    overriddenById: null,
    overrideJustification: null,
    createdAt: new Date("2025-06-15"),
  },
  lossHistoryOmission: {
    id: "fi-losshistory",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    documentId: null,
    category: "CROSS_DOC" as const,
    indicatorName: "LOSS_HISTORY_OMISSION",
    description: "ACORD 125 states no loss history but loss runs contain 3 claims",
    severity: "CRITICAL" as const,
    evidence: { lossDisclosure: false, lossRunClaimCount: 3 },
    confidence: 0.9,
    recommendedAction: "Investigate potential concealment",
    isOverridden: false,
    overriddenById: null,
    overrideJustification: null,
    createdAt: new Date("2025-06-15"),
  },
  roundNumbers: {
    id: "fi-round",
    submissionId: SUBMISSION.fraudulent.id,
    tenantId: TENANT.id,
    documentId: null,
    category: "STATISTICAL" as const,
    indicatorName: "ROUND_NUMBER_PATTERN",
    description: "Excessive round numbers in financial data",
    severity: "MEDIUM" as const,
    evidence: { roundNumberCount: 5, totalFields: 8, roundPercentage: 62.5 },
    confidence: 0.6,
    recommendedAction: "Review for potential data fabrication",
    isOverridden: false,
    overriddenById: null,
    overrideJustification: null,
    createdAt: new Date("2025-06-15"),
  },
};

export const WHITE_LABEL_CONFIG = {
  id: "wl-001",
  tenantId: TENANT.id,
  logoUrl: "https://acme.com/logo.png",
  primaryColor: "#1e40af",
  secondaryColor: "#3b82f6",
  accentColor: "#f59e0b",
  customDomain: "insurance.acme.com",
  customEmailDomain: "acme.com",
  termsUrl: "https://acme.com/terms",
  privacyUrl: "https://acme.com/privacy",
  footerText: "Acme Insurance MGA - All rights reserved",
  supportEmail: "support@acme.com",
  supportPhone: "1-800-ACME",
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-01"),
};
